# See https://github.com/actions/labeler#common-examples for defining patterns.
# The globs use "minimatch" syntax found at https://github.com/isaacs/minimatch
#
# WARNING: Due to this file being yaml, any string starting with `*` must be
# wrapped in quotes.

# Third-party tools
# TODO

# General areas
documentation:
- changed-files:
  - any-glob-to-any-file: [ "docs/*" , "docs/**/*", "*README*", "*.md", "*.rst", ".readthedocs.yml"]
github:
- changed-files:
  - any-glob-to-any-file: [ ".github/*", ".github/**/*"]
docker:
- changed-files:
  - any-glob-to-any-file: [ "Dockerfile", "*docker*"]
build:
- changed-files:
  - any-glob-to-any-file: [ "Makefile" , "*.make" , "CMakeLists.txt", "cmake" ]

# Tag pull requests with the languages used to make it easy to see what is
# being used.
lang-hdl:
- changed-files:
  - any-glob-to-any-file: [ "*.v", "*.sv"]
lang-cpp:
- changed-files:
  - any-glob-to-any-file: ["*.c*", "*.h"]
lang-perl:
- changed-files:
  - any-glob-to-any-file: [ "*.pl" , "*perl*" ]
lang-python:
- changed-files:
  - any-glob-to-any-file: [ "*.py" ]
lang-shell:
- changed-files:
  - any-glob-to-any-file: ["*.sh"]
lang-netlist:
- changed-files:
  - any-glob-to-any-file: [ "*.blif" , "*.eblif" ,"*.edif" , "*.vqm" ]
lang-make:
- changed-files:
  - any-glob-to-any-file: [ "*.make" , "Makefile" , "CMakeLists.txt" ]
