name: Increment Version

on:
  pull_request:
    types: [opened]

jobs:
  increment-patch-version:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Increment patch version
      run: |
        CURR_VERSION=$(grep "VERSION_PATCH" CMakeLists.txt | grep -Eo '[0-9]*')
        let "NEW_VERSION=CURR_VERSION+1"
        sed -i "s/VERSION_PATCH $CURR_VERSION/VERSION_PATCH $NEW_VERSION/g" CMakeLists.txt
        

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Incremented patch version'
        committer_name: GitHub Actions
        add: 'CMakeLists.txt'
